name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [master]
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build versioned docs
        working-directory: Doc
        run: poetry run sphinx-multiversion . _build/html

      - name: Generate versions.json
        run: |
          echo '[{"version": "master", "url": "/master/"}, {"version": "v1.0.2", "url": "/v1.0.2/"}, {"version": "v1.0.0", "url": "/v1.0.0/"}]' > build/versions.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Doc/_build/html
          publish_branch: gh-pages

